// <auto-generated />
using System;
using Listenfy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Listenfy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260219112653_AddHasSentWelcomeMessageToGuildSettings")]
    partial class AddHasSentWelcomeMessageToGuildSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Listenfy.Domain.Models.GuildSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscordGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasSentWelcomeMessage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("StatsChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("WeeklySummaryDay")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("WeeklySummaryTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("DiscordGuildId")
                        .IsUnique();

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("Listenfy.Domain.Models.ListeningHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextType")
                        .HasColumnType("text");

                    b.Property<string>("ContextUri")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpotifyUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpotifyUserId", "TrackId", "PlayedAt")
                        .IsUnique();

                    b.ToTable("ListeningHistories");
                });

            modelBuilder.Entity("Listenfy.Domain.Models.SpotifyFetchMetadata", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpotifyUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TracksFetchedInLastRun")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpotifyUserId")
                        .IsUnique();

                    b.ToTable("SpotifyFetchMetadata");
                });

            modelBuilder.Entity("Listenfy.Domain.Models.SpotifyUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpotifyUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SpotifyUsers");
                });

            modelBuilder.Entity("Listenfy.Domain.Models.UserConnection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OAuthState")
                        .HasColumnType("text");

                    b.Property<string>("SpotifyUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpotifyUserId");

                    b.HasIndex("GuildId", "DiscordUserId")
                        .IsUnique();

                    b.ToTable("UserConnections");
                });

            modelBuilder.Entity("Listenfy.Domain.Models.WeeklyStat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpotifyUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalMinutesListened")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTracksPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueTracksPlayed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeekIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SpotifyUserId");

                    b.ToTable("WeeklyStats");
                });

            modelBuilder.Entity("Listenfy.Domain.Models.ListeningHistory", b =>
                {
                    b.HasOne("Listenfy.Domain.Models.SpotifyUser", "SpotifyUser")
                        .WithMany("ListeningHistories")
                        .HasForeignKey("SpotifyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Listenfy.Domain.Models.Artist", "Artists", b1 =>
                        {
                            b1.Property<string>("ListeningHistoryId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Id");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("ListeningHistoryId", "__synthesizedOrdinal");

                            b1.ToTable("ListeningHistories");

                            b1
                                .ToJson("Artists")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ListeningHistoryId");
                        });

                    b.Navigation("Artists");

                    b.Navigation("SpotifyUser");
                });

            modelBuilder.Entity("Listenfy.Domain.Models.SpotifyFetchMetadata", b =>
                {
                    b.HasOne("Listenfy.Domain.Models.SpotifyUser", "SpotifyUser")
                        .WithOne("SpotifyFetchMetadata")
                        .HasForeignKey("Listenfy.Domain.Models.SpotifyFetchMetadata", "SpotifyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpotifyUser");
                });

            modelBuilder.Entity("Listenfy.Domain.Models.UserConnection", b =>
                {
                    b.HasOne("Listenfy.Domain.Models.GuildSettings", "Guild")
                        .WithMany("UserConnections")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Listenfy.Domain.Models.SpotifyUser", "SpotifyUser")
                        .WithMany("UserConnections")
                        .HasForeignKey("SpotifyUserId");

                    b.Navigation("Guild");

                    b.Navigation("SpotifyUser");
                });

            modelBuilder.Entity("Listenfy.Domain.Models.WeeklyStat", b =>
                {
                    b.HasOne("Listenfy.Domain.Models.SpotifyUser", "SpotifyUser")
                        .WithMany("WeeklyStats")
                        .HasForeignKey("SpotifyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Listenfy.Domain.Models.TopArtist", "TopArtists", b1 =>
                        {
                            b1.Property<string>("WeeklyStatId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Id");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("PlayCount");

                            b1.HasKey("WeeklyStatId", "__synthesizedOrdinal");

                            b1.ToTable("WeeklyStats");

                            b1
                                .ToJson("TopArtists")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WeeklyStatId");
                        });

                    b.OwnsMany("Listenfy.Domain.Models.TopTrack", "TopTracks", b1 =>
                        {
                            b1.Property<string>("WeeklyStatId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("ArtistDisplay")
                                .IsRequired();

                            b1.Property<string>("Id");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("PlayCount");

                            b1.HasKey("WeeklyStatId", "__synthesizedOrdinal");

                            b1.ToTable("WeeklyStats");

                            b1
                                .ToJson("TopTracks")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WeeklyStatId");
                        });

                    b.Navigation("SpotifyUser");

                    b.Navigation("TopArtists");

                    b.Navigation("TopTracks");
                });

            modelBuilder.Entity("Listenfy.Domain.Models.GuildSettings", b =>
                {
                    b.Navigation("UserConnections");
                });

            modelBuilder.Entity("Listenfy.Domain.Models.SpotifyUser", b =>
                {
                    b.Navigation("ListeningHistories");

                    b.Navigation("SpotifyFetchMetadata");

                    b.Navigation("UserConnections");

                    b.Navigation("WeeklyStats");
                });
#pragma warning restore 612, 618
        }
    }
}
